Repository kubeflow/community-infra, pull requests merged in 2020-10, with the labels that each got.

#21 added infrastructure specs for community calendar
  prod/namespaces/kf-infra-gitops/iam-policy-members.yaml
  prod/namespaces/kf-infra-gitops/namespace.yaml
  prod/namespaces/kf-infra-gitops/project.yaml
Labels: approved, cla: yes, lgtm, size/S

#22 creates "kf-infra-gitops-sa" IAMService Account
  prod/namespaces/kf-infra-gitops/iam-service-accounts.yaml
Labels: approved, cla: yes, lgtm, size/XS

#23 Create a GKE cluster for running the calendar sync and other automation.
  prod/namespaces/kf-infra-gitops/cluster.yaml
Labels: approved, cla: yes, lgtm, size/M

#24 * Fix config bug.
  Makefile
  prod/namespaces/kf-infra-gitops/cluster.yaml
Labels: approved, cla: yes

#25 Enroll the cluster in the regular channel.
  prod/namespaces/kf-infra-gitops/cluster.yaml
Labels: approved, cla: yes, size/XS

#26 Fix nodepool.
  prod/namespaces/kf-infra-gitops/cluster.yaml
Labels: approved, cla: yes

#27 Fix nodepool oauthscopes.
  prod/namespaces/kf-infra-gitops/cluster.yaml
Labels: approved, cla: yes, size/XS

#29 Throw together some go code to cleanup kubeflow.org GCP
  tools/Makefile
  tools/cmd/main.go
  tools/go.mod
  tools/go.sum
  tools/manifests/bulk_delete.yaml
  tools/manifests/bulk_delete_load_test.yaml
  tools/manifests/bulk_move.yaml
  tools/manifests/more_projects.yaml
  tools/pkg/api/v1alpha1/types.go
  tools/pkg/controllers/bulk_delete.go
  tools/pkg/controllers/bulk_move.go
  tools/pkg/controllers/org_helper.go
  tools/pkg/utils/kinds.go
Labels: approved, cla: yes, lgtm, size/XXL
