Repository kubeflow/community-infra, pull requests merged in 2020-09, with the labels that each got.

#11 Add AutoML project
  prod/namespaces/automl/iam-policy-members.yaml
  prod/namespaces/automl/namespace.yaml
  prod/namespaces/automl/project.yaml
Labels: approved, lgtm, size/M

#16 Rename AutoML project to make it unique
  prod/namespaces/automl-ci/iam-policy-members.yaml
  prod/namespaces/automl-ci/namespace.yaml
  prod/namespaces/automl-ci/project.yaml
Labels: approved, lgtm, size/S

#17 Change KFServing members to editor
  prod/namespaces/kfserving/iam-policy-members.yaml
Labels: approved, lgtm, size/XS

#18 Add necessary roles for CI service account in AutoML project
  prod/namespaces/automl-ci/iam-policy-members.yaml
Labels: approved, lgtm, size/S

#19 Modify doc for creating new project
  README.md
Labels: approved, lgtm, size/M

#20 Update OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS
